In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
bb_df = pd.read_csv("Resources/CleanHoopsData.csv")
bb_df.head()

,Year,Player,Pos,Age,Height,Weight,Tm,G,MP,PTS,...,FG%,3P,3PA,3P%,2P,2PA,2P%,FT,FTA,FT%
0,1979.0,Kareem Abdul-Jabbar*,C,31.0,218.0,102.0,LAL,80.0,39.46,23.79,...,0.577,0.0,0.0,0.0,9.71,16.84,0.577,4.36,5.92,0.736
1,1979.0,Tom Abernethy,PF,24.0,201.0,99.0,GSW,70.0,17.41,6.03,...,0.515,0.0,0.0,0.0,2.51,4.89,0.515,1.00,1.34,0.745
2,1979.0,Alvan Adams,C,24.0,206.0,95.0,PHO,77.0,30.70,17.78,...,0.530,0.0,0.0,0.0,7.39,13.94,0.530,3.00,3.75,0.799
3,1979.0,Lucius Allen,PG,31.0,188.0,79.0,KCK,31.0,13.32,5.06,...,0.397,0.0,0.0,0.0,2.23,5.61,0.397,0.61,1.06,0.576
4,1979.0,Kim Anderson,SF,23.0,201.0,90.0,POR,21.0,10.67,3.00,...,0.312,0.0,0.0,0.0,1.14,3.67,0.312,0.71,1.33,0.536

In [3]:
bb_df['Pos'] = bb_df['Pos'].map({'PG':1, 'SG':2, 'SF':3, 'PF':4,'C':5})

In [4]:
bb_df['BMI'] = bb_df['Weight'] / ((bb_df['Height']/100)*(bb_df['Height']/100))

In [5]:
target = bb_df['Pos'].values.reshape(-1,1)
target_names = ['PG','SG','SF','PF','C']

In [6]:
player_names = bb_df['Player']

In [7]:
data = bb_df.drop(['Tm','Player','Pos', 'Height','Weight'], axis=1)
feature_names = data.columns
data.head()

,Year,Age,G,MP,PTS,AST,TRB,ORB,DRB,STL,...,3P,3PA,3P%,2P,2PA,2P%,FT,FTA,FT%,BMI
0,1979.0,31.0,80.0,39.46,23.79,5.39,12.81,2.59,10.22,0.95,...,0.0,0.0,0.0,9.71,16.84,0.577,4.36,5.92,0.736,21.462840
1,1979.0,24.0,70.0,17.41,6.03,1.13,3.09,1.06,2.03,0.56,...,0.0,0.0,0.0,2.51,4.89,0.515,1.00,1.34,0.745,24.504344
2,1979.0,24.0,77.0,30.70,17.78,4.68,9.16,2.86,6.30,1.43,...,0.0,0.0,0.0,7.39,13.94,0.530,3.00,3.75,0.799,22.386653
3,1979.0,31.0,31.0,13.32,5.06,1.42,1.48,0.45,1.03,0.68,...,0.0,0.0,0.0,2.23,5.61,0.397,0.61,1.06,0.576,22.351743
4,1979.0,23.0,21.0,10.67,3.00,0.71,2.14,0.81,1.33,0.19,...,0.0,0.0,0.0,1.14,3.67,0.312,0.71,1.33,0.536,22.276676

In [8]:
list(data.columns)

['Year',
 'Age',
 'G',
 'MP',
 'PTS',
 'AST',
 'TRB',
 'ORB',
 'DRB',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PER',
 'VORP',
 'BPM',
 'TS%',
 'eFG%',
 'USG%',
 'AST%',
 'TRB%',
 'ORB%',
 'DRB%',
 'STL%',
 'BLK%',
 'TOV%',
 'FG',
 'FGA',
 'FG%',
 '3P',
 '3PA',
 '3P%',
 '2P',
 '2PA',
 '2P%',
 'FT',
 'FTA',
 'FT%',
 'BMI']

In [9]:
data['Year'] = data['Year'] - 1978
data.head()

,Year,Age,G,MP,PTS,AST,TRB,ORB,DRB,STL,...,3P,3PA,3P%,2P,2PA,2P%,FT,FTA,FT%,BMI
0,1.0,31.0,80.0,39.46,23.79,5.39,12.81,2.59,10.22,0.95,...,0.0,0.0,0.0,9.71,16.84,0.577,4.36,5.92,0.736,21.462840
1,1.0,24.0,70.0,17.41,6.03,1.13,3.09,1.06,2.03,0.56,...,0.0,0.0,0.0,2.51,4.89,0.515,1.00,1.34,0.745,24.504344
2,1.0,24.0,77.0,30.70,17.78,4.68,9.16,2.86,6.30,1.43,...,0.0,0.0,0.0,7.39,13.94,0.530,3.00,3.75,0.799,22.386653
3,1.0,31.0,31.0,13.32,5.06,1.42,1.48,0.45,1.03,0.68,...,0.0,0.0,0.0,2.23,5.61,0.397,0.61,1.06,0.576,22.351743
4,1.0,23.0,21.0,10.67,3.00,0.71,2.14,0.81,1.33,0.19,...,0.0,0.0,0.0,1.14,3.67,0.312,0.71,1.33,0.536,22.276676

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [11]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

In [12]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [13]:
from sklearn.svm import SVC 
model = SVC(kernel='linear')

In [14]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [1, 5, 10],
              'gamma': [0.0001, 0.001, 0.01]}
grid = GridSearchCV(model, param_grid, verbose=3)

In [15]:
grid.fit(X_train_scaled, y_train.ravel())

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV] C=1, gamma=0.0001 ...............................................

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV] ................... C=1, gamma=0.0001, score=0.656, total=   7.8s
[CV] C=1, gamma=0.0001 ...............................................

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    7.7s remaining:    0.0s

[CV] ................... C=1, gamma=0.0001, score=0.653, total=   7.3s
[CV] C=1, gamma=0.0001 ...............................................

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   15.0s remaining:    0.0s

[CV] ................... C=1, gamma=0.0001, score=0.658, total=   7.5s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.647, total=  10.1s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................... C=1, gamma=0.0001, score=0.663, total=   8.3s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.656, total=   8.1s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.653, total=   8.0s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.658, total=   8.0s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.647, total=   9.2s
[CV] C=1, gamma=0.001 ................................................
[CV] .................... C=1, gamma=0.001, score=0.663, total=   8.1s
[CV] C=1, gamma=0.01 .................................................
[CV] ..................... C=1, gamma=0.01, score=0.656, total=   8.6s
[CV] C=1, gamma=0.01 .................................................
[CV] ..................... C=1, gamma=0.01, score=0.653, total=   7.7s
[CV] C=1, gamma=0.01 .................................................
[CV] ..................... C=1, gamma=0.01, score=0.658, total=   7.8s
[CV] C=1, gamma=0.01 .................................................
[CV] ..................... C=1, gamma=0.01, score=0.647, total=   7.7s
[CV] C=1, gamma=0.01 .................................................
[CV] ..................... C=1, gamma=0.01, score=0.663, total=   7.9s
[CV] C=5, gamma=0.0001 ...............................................
[CV] ................... C=5, gamma=0.0001, score=0.657, total=  19.2s
[CV] C=5, gamma=0.0001 ...............................................
[CV] ................... C=5, gamma=0.0001, score=0.654, total=  21.4s
[CV] C=5, gamma=0.0001 ...............................................
[CV] ................... C=5, gamma=0.0001, score=0.659, total=  19.5s
[CV] C=5, gamma=0.0001 ...............................................
[CV] ................... C=5, gamma=0.0001, score=0.645, total=  20.2s
[CV] C=5, gamma=0.0001 ...............................................
[CV] ................... C=5, gamma=0.0001, score=0.662, total=  19.1s
[CV] C=5, gamma=0.001 ................................................
[CV] .................... C=5, gamma=0.001, score=0.657, total=  18.8s
[CV] C=5, gamma=0.001 ................................................
[CV] .................... C=5, gamma=0.001, score=0.654, total=  18.2s
[CV] C=5, gamma=0.001 ................................................
[CV] .................... C=5, gamma=0.001, score=0.659, total=  22.0s
[CV] C=5, gamma=0.001 ................................................
[CV] .................... C=5, gamma=0.001, score=0.645, total=  18.3s
[CV] C=5, gamma=0.001 ................................................
[CV] .................... C=5, gamma=0.001, score=0.662, total=  19.0s
[CV] C=5, gamma=0.01 .................................................
[CV] ..................... C=5, gamma=0.01, score=0.657, total=  19.7s
[CV] C=5, gamma=0.01 .................................................
[CV] ..................... C=5, gamma=0.01, score=0.654, total=  18.3s
[CV] C=5, gamma=0.01 .................................................
[CV] ..................... C=5, gamma=0.01, score=0.659, total=  21.3s
[CV] C=5, gamma=0.01 .................................................
[CV] ..................... C=5, gamma=0.01, score=0.645, total=  25.3s
[CV] C=5, gamma=0.01 .................................................
[CV] ..................... C=5, gamma=0.01, score=0.662, total=  20.3s
[CV] C=10, gamma=0.0001 ..............................................
[CV] .................. C=10, gamma=0.0001, score=0.658, total=  32.9s
[CV] C=10, gamma=0.0001 ..............................................
[CV] .................. C=10, gamma=0.0001, score=0.654, total=  33.8s
[CV] C=10, gamma=0.0001 ..............................................
[CV] .................. C=10, gamma=0.0001, score=0.658, total=  46.2s
[CV] C=10, gamma=0.0001 ..............................................
[CV] .................. C=10, gamma=0.0001, score=0.646, total=  32.9s
[CV] C=10, gamma=0.0001 ..............................................
[CV] .................. C=10, gamma=0.0001, score=0.662, total=  32.7s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................... C=10, gamma=0.001, score=0.658, total=  39.1s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................... C=10, gamma=0.001, score=0.654, total=  32.1s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................... C=10, gamma=0.001, score=0.658, total=  33.8s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................... C=10, gamma=0.001, score=0.646, total=  37.6s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................... C=10, gamma=0.001, score=0.662, total=  37.4s
[CV] C=10, gamma=0.01 ................................................
[CV] .................... C=10, gamma=0.01, score=0.658, total=  35.4s
[CV] C=10, gamma=0.01 ................................................
[CV] .................... C=10, gamma=0.01, score=0.654, total=  32.9s
[CV] C=10, gamma=0.01 ................................................
[CV] .................... C=10, gamma=0.01, score=0.658, total=  39.2s
[CV] C=10, gamma=0.01 ................................................
[CV] .................... C=10, gamma=0.01, score=0.646, total=  35.7s
[CV] C=10, gamma=0.01 ................................................
[CV] .................... C=10, gamma=0.01, score=0.662, total=  35.0s

[Parallel(n_jobs=1)]: Done  45 out of  45 | elapsed: 16.0min finished

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [1, 5, 10], 'gamma': [0.0001, 0.001, 0.01]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [16]:
print(grid.best_params_)

{'C': 10, 'gamma': 0.0001}

In [17]:
print(grid.best_score_)

0.6558243714075943

In [18]:
predictions = grid.predict(X_test_scaled)

In [19]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions,
                            target_names=target_names))

              precision    recall  f1-score   support

          PG       0.83      0.86      0.84       969
          SG       0.64      0.61      0.63       969
          SF       0.59      0.60      0.59       917
          PF       0.56      0.54      0.55       984
           C       0.68      0.71      0.69       978

    accuracy                           0.66      4817
   macro avg       0.66      0.66      0.66      4817
weighted avg       0.66      0.66      0.66      4817